services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    networks:
      - opencourt-net

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - opencourt-net

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./src/database/create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql
      - ./src/database/seed_tables.sql:/docker-entrypoint-initdb.d/2_seed_tables.sql
    networks:
      - opencourt-net

networks:
  opencourt-net:
    driver: bridge

volumes:
  db-data: